import { requirePlatformAdmin } from "../_lib/auth.js";
import { getSupabaseAdmin } from "../_lib/supabaseAdmin.js";

function text(value: unknown, max = 4000) {
  return typeof value === "string" ? value.trim().slice(0, max) : "";
}
function id(value: unknown) { return text(value, 100); }
function positiveInt(value: unknown, fallback: number) {
  const result = Number(value);
  return Number.isInteger(result) && result > 0 ? result : fallback;
}
function cents(value: unknown): number | null {
  const result = Number(value);
  return Number.isInteger(result) && result > 0 ? result : null;
}

type ContractData = {
  projectSummary: string;
  deliverables: string;
  clientResponsibilities: string;
  assumptions: string;
  exclusions: string;
  paymentTerms: string;
  specialTerms: string;
};

function structuredContractData(value: unknown): ContractData {
  const source = value && typeof value === "object" ? value as Record<string, unknown> : {};
  return {
    projectSummary: text(source.projectSummary, 5000),
    deliverables: text(source.deliverables, 12000),
    clientResponsibilities: text(source.clientResponsibilities, 12000),
    assumptions: text(source.assumptions, 12000),
    exclusions: text(source.exclusions, 12000),
    paymentTerms: text(source.paymentTerms, 1000),
    specialTerms: text(source.specialTerms, 12000),
  };
}

function listText(value: string, fallback: string) {
  const items = value.split(/\r?\n/).map(item => item.replace(/^[-•*]\s*/, "").trim()).filter(Boolean);
  return items.length > 0 ? items.map(item => `- ${item}`).join("\n") : fallback;
}

function contractTemplate(input: {
  companyName: string;
  title: string;
  serviceType: string;
  scope: string;
  billingModel: string;
  rateCents: number | null;
  startDate: string;
  endDate: string;
  contractData: ContractData;
}) {
  const rate = input.rateCents === null
    ? "as stated in the applicable statement of work"
    : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(input.rateCents / 100);
  const term = input.endDate
    ? `${input.startDate || "a mutually agreed date"} through ${input.endDate}`
    : `beginning ${input.startDate || "on a mutually agreed date"}`;

  return `${input.title}\n\nPARTIES\nThis agreement is between OneTime Labs and ${input.companyName}.\n\n1. PROJECT SUMMARY\n${input.contractData.projectSummary || `OneTime Labs will provide ${input.serviceType} services for ${input.companyName}.`}\n\n2. SERVICES AND TERM\nOneTime Labs will provide ${input.serviceType} services ${term}.\n\n3. SCOPE OF WORK\n${input.scope || "Scope and deliverables will be documented and approved before work begins."}\n\n4. DELIVERABLES\n${listText(input.contractData.deliverables, "Deliverables will be defined and confirmed before work begins.")}\n\n5. CLIENT RESPONSIBILITIES\n${listText(input.contractData.clientResponsibilities, "- Provide timely access to personnel, systems, vendors, documentation, facilities, and approvals reasonably required to perform the work.")}\n\n6. FEES AND PAYMENT\nBilling model: ${input.billingModel}. Rate or engagement amount: ${rate}. Payment terms: ${input.contractData.paymentTerms || "as shown on each invoice"}. Approved third-party costs, travel, hardware, software licensing, and unusual-hours work may be billed separately when agreed in writing.\n\n7. ASSUMPTIONS\n${listText(input.contractData.assumptions, "- Work is based on information and access supplied by the client.")}\n\n8. EXCLUSIONS\n${listText(input.contractData.exclusions, "- Work not expressly included in the approved scope is excluded unless added through written change control.")}\n\n9. CHANGE CONTROL\nMaterial changes to scope, assumptions, schedule, or deliverables require written approval and may change fees or delivery dates.\n\n10. CONFIDENTIALITY AND DATA\nEach party will use reasonable care with confidential information received during the engagement and will use that information only for the work described in this agreement.\n\n11. OWNERSHIP\nPre-existing tools, reusable methods, frameworks, and OneTime Labs software remain the property of their respective owners. Client-specific deliverables and any separately licensed software are governed by the applicable statement of work or license terms.\n\n12. TERMINATION\nEither party may end the engagement by written notice. The client remains responsible for work performed and approved costs incurred through the effective termination date.\n\n13. SPECIAL TERMS\n${input.contractData.specialTerms || "No additional special terms."}\n\n14. ENTIRE AGREEMENT\nThis agreement and any attached or referenced statement of work describe the consulting engagement and may be amended only in writing by both parties.\n\nCLIENT: ${input.companyName}\n\nONETIME LABS\n\nDraft generated by OneTime Labs Platform. Review before execution.`;
}

async function stripeRequest(path: string, body?: URLSearchParams) {
  const secret = process.env.STRIPE_SECRET_KEY?.trim();
  if (!secret) throw new Error("STRIPE_NOT_CONFIGURED");
  const response = await fetch(`https://api.stripe.com/v1${path}`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${secret}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body,
  });
  const payload = await response.json() as Record<string, any>;
  if (!response.ok) throw new Error(payload?.error?.message || `Stripe request failed (${response.status}).`);
  return payload;
}

function mapClient(row: any) {
  return { id: row.id, companyName: row.company_name, contactName: row.contact_name, email: row.email, phone: row.phone, billingAddress: row.billing_address, notes: row.notes, stripeCustomerId: row.stripe_customer_id, active: row.active, createdAt: row.created_at };
}
function mapContract(row: any) {
  return {
    id: row.id,
    clientId: row.client_id,
    title: row.title,
    serviceType: row.service_type,
    templateKey: row.template_key ?? "legacy",
    status: row.status,
    startDate: row.start_date,
    endDate: row.end_date,
    billingModel: row.billing_model,
    rateCents: row.rate_cents,
    currency: row.currency,
    scope: row.scope,
    contractData: structuredContractData(row.contract_data),
    contractText: row.contract_text,
    acceptedAt: row.accepted_at,
    acceptedBy: row.accepted_by,
    createdAt: row.created_at,
  };
}
function mapInvoice(row: any) {
  return { id: row.id, clientId: row.client_id, contractId: row.contract_id, stripeInvoiceId: row.stripe_invoice_id, stripeInvoiceUrl: row.stripe_invoice_url, status: row.status, description: row.description, amountCents: row.amount_cents, currency: row.currency, dueDays: row.due_days, createdAt: row.created_at, sentAt: row.sent_at };
}

export default async function handler(req: any, res: any) {
  res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate");
  try {
    await requirePlatformAdmin(req.headers?.authorization);
    const supabase = getSupabaseAdmin();

    if (req.method === "GET") {
      const [clientsResult, contractsResult, invoicesResult] = await Promise.all([
        supabase.from("consulting_clients").select("*").order("company_name"),
        supabase.from("consulting_contracts").select("*").order("created_at", { ascending: false }),
        supabase.from("consulting_invoices").select("*").order("created_at", { ascending: false }),
      ]);
      if (clientsResult.error) throw clientsResult.error;
      if (contractsResult.error) throw contractsResult.error;
      if (invoicesResult.error) throw invoicesResult.error;
      res.status(200).json({
        clients: (clientsResult.data ?? []).map(mapClient),
        contracts: (contractsResult.data ?? []).map(mapContract),
        invoices: (invoicesResult.data ?? []).map(mapInvoice),
        stripeConfigured: Boolean(process.env.STRIPE_SECRET_KEY?.trim()),
      });
      return;
    }

    if (req.method !== "POST") {
      res.setHeader("Allow", "GET, POST");
      res.status(405).json({ error: "Method not allowed." });
      return;
    }

    const action = text(req.body?.action, 40);

    if (action === "client-create") {
      const companyName = text(req.body?.companyName, 180);
      if (!companyName) { res.status(400).json({ error: "Company name is required." }); return; }
      const { data, error } = await supabase.from("consulting_clients").insert({
        company_name: companyName,
        contact_name: text(req.body?.contactName, 160) || null,
        email: text(req.body?.email, 240) || null,
        phone: text(req.body?.phone, 80) || null,
        billing_address: text(req.body?.billingAddress, 1000) || null,
        notes: text(req.body?.notes, 4000) || null,
      }).select("id").single();
      if (error) throw error;
      res.status(201).json({ id: data.id }); return;
    }

    if (action === "contract-create") {
      const clientId = id(req.body?.clientId);
      const title = text(req.body?.title, 220);
      if (!clientId || !title) { res.status(400).json({ error: "Client and agreement title are required." }); return; }
      const { data: client, error: clientError } = await supabase.from("consulting_clients").select("id, company_name").eq("id", clientId).maybeSingle();
      if (clientError) throw clientError;
      if (!client) { res.status(404).json({ error: "Client was not found." }); return; }
      const billingModel = text(req.body?.billingModel, 20) || "hourly";
      if (!["hourly","daily","fixed","retainer"].includes(billingModel)) { res.status(400).json({ error: "Invalid billing model." }); return; }
      const serviceType = text(req.body?.serviceType, 160) || "Consulting";
      const templateKey = text(req.body?.templateKey, 80) || "consulting";
      const scope = text(req.body?.scope, 12000);
      const startDate = text(req.body?.startDate, 10);
      const endDate = text(req.body?.endDate, 10);
      const rateCents = cents(req.body?.rateCents);
      const contractData = structuredContractData(req.body?.contractData);
      const contractText = contractTemplate({
        companyName: client.company_name,
        title,
        serviceType,
        scope,
        billingModel,
        rateCents,
        startDate,
        endDate,
        contractData,
      });
      const { data, error } = await supabase.from("consulting_contracts").insert({
        client_id: clientId,
        title,
        service_type: serviceType,
        template_key: templateKey,
        billing_model: billingModel,
        rate_cents: rateCents,
        start_date: startDate || null,
        end_date: endDate || null,
        scope: scope || null,
        contract_data: contractData,
        contract_text: contractText,
      }).select("id").single();
      if (error) throw error;
      res.status(201).json({ id: data.id }); return;
    }

    if (action === "contract-status") {
      const contractId = id(req.body?.contractId);
      const status = text(req.body?.status, 20);
      if (!contractId || !["draft","sent","accepted","completed","cancelled"].includes(status)) { res.status(400).json({ error: "Valid contract ID and status are required." }); return; }
      const patch: Record<string, unknown> = { status, updated_at: new Date().toISOString() };
      if (status === "accepted") { patch.accepted_at = new Date().toISOString(); patch.accepted_by = text(req.body?.acceptedBy, 180) || null; }
      const { error } = await supabase.from("consulting_contracts").update(patch).eq("id", contractId);
      if (error) throw error;
      res.status(200).json({ updated: true }); return;
    }

    if (action === "invoice-create") {
      const clientId = id(req.body?.clientId);
      const contractId = id(req.body?.contractId) || null;
      const description = text(req.body?.description, 500);
      const amountCents = cents(req.body?.amountCents);
      const dueDays = Math.min(365, positiveInt(req.body?.dueDays, 30));
      if (!clientId || !description || !amountCents) { res.status(400).json({ error: "Client, description, and invoice amount are required." }); return; }
      const { data: client, error: clientError } = await supabase.from("consulting_clients").select("*").eq("id", clientId).maybeSingle();
      if (clientError) throw clientError;
      if (!client) { res.status(404).json({ error: "Client was not found." }); return; }
      let stripeCustomerId = client.stripe_customer_id as string | null;
      if (!stripeCustomerId) {
        const customerBody = new URLSearchParams();
        customerBody.set("name", client.company_name);
        if (client.email) customerBody.set("email", client.email);
        if (client.contact_name) customerBody.set("description", `OneTime Labs consulting client — ${client.contact_name}`);
        customerBody.set("metadata[platform_client_id]", client.id);
        const customer = await stripeRequest("/customers", customerBody);
        stripeCustomerId = customer.id as string;
        const { error } = await supabase.from("consulting_clients").update({ stripe_customer_id: stripeCustomerId, updated_at: new Date().toISOString() }).eq("id", clientId);
        if (error) throw error;
      }
      // Create the draft invoice first. Stripe's standalone invoice creation currently
      // excludes unattached pending invoice items by default, which previously produced
      // $0 invoices while leaving the intended charge stranded as a pending item.
      const invoiceBody = new URLSearchParams();
      invoiceBody.set("customer", stripeCustomerId);
      invoiceBody.set("collection_method", "send_invoice");
      invoiceBody.set("days_until_due", String(dueDays));
      invoiceBody.set("auto_advance", "false");

      // Explicitly allow card and US bank account (ACH Direct Debit) payments.
      // Stripe owns collection, bank-account linking, verification, and mandate handling.
      invoiceBody.set("payment_settings[payment_method_types][0]", "card");
      invoiceBody.set("payment_settings[payment_method_types][1]", "us_bank_account");
      invoiceBody.set(
        "payment_settings[payment_method_options][us_bank_account][verification_method]",
        "automatic",
      );

      invoiceBody.set("metadata[platform_client_id]", clientId);
      if (contractId) invoiceBody.set("metadata[platform_contract_id]", contractId);

      const stripeInvoice = await stripeRequest("/invoices", invoiceBody);

      // Attach this exact line item to this exact draft invoice. This is deterministic
      // and prevents unrelated pending items for the same customer from being swept in.
      const itemBody = new URLSearchParams();
      itemBody.set("customer", stripeCustomerId);
      itemBody.set("invoice", stripeInvoice.id);
      itemBody.set("amount", String(amountCents));
      itemBody.set("currency", "usd");
      itemBody.set("description", description);
      await stripeRequest("/invoiceitems", itemBody);
      const { data, error } = await supabase.from("consulting_invoices").insert({
        client_id: clientId, contract_id: contractId, stripe_invoice_id: stripeInvoice.id,
        stripe_invoice_url: stripeInvoice.hosted_invoice_url ?? null, status: stripeInvoice.status ?? "draft",
        description, amount_cents: amountCents, due_days: dueDays,
      }).select("id").single();
      if (error) throw error;
      res.status(201).json({ id: data.id, stripeInvoiceId: stripeInvoice.id, url: stripeInvoice.hosted_invoice_url ?? null }); return;
    }

    if (action === "invoice-send") {
      const invoiceId = id(req.body?.invoiceId);
      const { data: invoice, error: invoiceError } = await supabase.from("consulting_invoices").select("id, stripe_invoice_id").eq("id", invoiceId).maybeSingle();
      if (invoiceError) throw invoiceError;
      if (!invoice?.stripe_invoice_id) { res.status(404).json({ error: "Stripe invoice was not found." }); return; }
      const stripeInvoice = await stripeRequest(`/invoices/${encodeURIComponent(invoice.stripe_invoice_id)}/send`);
      const { error } = await supabase.from("consulting_invoices").update({
        status: stripeInvoice.status ?? "open", stripe_invoice_url: stripeInvoice.hosted_invoice_url ?? null,
        sent_at: new Date().toISOString(), updated_at: new Date().toISOString(),
      }).eq("id", invoiceId);
      if (error) throw error;
      res.status(200).json({ sent: true, url: stripeInvoice.hosted_invoice_url ?? null }); return;
    }

    res.status(400).json({ error: "Unknown consulting action." });
  } catch (reason) {
    let message = "Unexpected consulting error.";

    if (reason instanceof Error) {
      message = reason.message;
    } else if (
      reason &&
      typeof reason === "object" &&
      "message" in reason &&
      typeof (reason as { message?: unknown }).message === "string"
    ) {
      message = (reason as { message: string }).message;
    }

    if (message === "AUTH_REQUIRED") { res.status(401).json({ error: "Sign in to Platform." }); return; }
    if (message === "ADMIN_REQUIRED") { res.status(403).json({ error: "Platform administrator access is required." }); return; }
    if (message === "STRIPE_NOT_CONFIGURED") { res.status(503).json({ error: "Stripe is not configured. Add STRIPE_SECRET_KEY to Platform." }); return; }
    console.error("CONSULTING API ERROR:", reason);
    res.status(500).json({ error: message });
  }
}
